name: xk8sAPI
version: 'v0.0.1-RC01'
main: de.pixelplayer_studios.xkubernetes.xKubernetes
api-version: '1.20'
author: PixelPlayer Studios
commands:
  kubernetes:
    aliases: kubectl, kubeman, kubeadmn